name: CI Pipeline

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    #  - name: Set up JDK 11
     #   uses: actions/setup-java@v2
      #  with:
       #   java-version: '11'

      - name: Run Tests
        run: |
          cd project
          java -cp "./Plugins/*" "-DenvToUse=${{ vars.ENVTOUSE }}" io.cucumber.core.cli.Main \
          --plugin "me.jvt.cucumber.report.PrettyReports:./target" \
          --plugin "html:./target/cucumber" \
          --plugin "json:./target/cucumber-json/cucumber.json" \
          --plugin "pretty" \
          "./src/test/resources/features" \
          --glue "com.accenture.stepdefs" \
        #  "--tags" "${{ env.TAGS_TO_RUN }}"
       # env:
        #  ENV_TO_USE: ${{ secrets.ENV_TO_USE }}
         # TAGS_TO_RUN: ${{ secrets.TAGS_TO_RUN }}

      - name: Publish Cucumber Business Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CucumberBusinessResults
          path: project/target/cucumber-html-reports

      - name: Publish Extend Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CAFResults
          path: project/Report.html

      - name: Publish Test Video
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestExecutionVideo
          path: project/target/testRecordings
