on: workflow_dispatch
    jobs:
    runs-on: [self-hosted, linux, x64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Java 21 in Windows
        if: runner.os == 'Windows'
        run: |
          java -version 2>&1 | findstr /C:"version \"21"
          if %errorlevel% == 0 (
            echo Java 21 is installed
          ) else (
            echo Java 21 is not installed
            exit 1
          )

      - name: Validate Java 21 in Linux or Mac
        if: runner.os != 'Windows'
        run: |
          if java -version 2>&1 | grep -q "version \"21"; then
            echo "Java 21 is installed"
          else
            echo "Java 21 is not installed"
            exit 1
          fi
