on: workflow_dispatch

jobs:
  validate-java:
    runs-on: [self-hosted, linux, x64]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      #- name: Set up Java 21
       # uses: actions/setup-java@v3
        #with:
         # java-version: '21'
          #distribution: 'adopt'

      - name: Validate Java 21
        run: |
          java -version 2>&1 | grep "version \"21" && echo "Java 21 is installed" || (echo "Java 21 is not installed" && exit 1)
        shell: bash
        if: runner.os != 'Windows'

      - name: Validate Java 21 on Windows
        run: |
          java -version 2>&1 | findstr /C:"version \"21"
          if %errorlevel% == 0 (
            echo Java 21 is installed
          ) else (
            echo Java 21 is not installed
            exit 1
          )
        shell: cmd
        if: runner.os == 'Windows'
