name: CI Pipeline

on: [push, pull_request]

jobs:
  generate-token:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate access_token
        id: generate_token
        run: |
          ACCESS_TOKEN=$(curl -X POST 'https://keycloakdev.codelessauto.io/realms/test/protocol/openid-connect/token' \
          -H 'Content-Type: application/x-www-form-urlencoded' \
          -d 'client_id=caf-client.staging' \
          -d 'grant_type=password' \
          -d "username=ctasacceptanceid@accenture.com" \
          -d "password=ctas@2024" | jq -r '.access_token')

          if [ -z "$ACCESS_TOKEN" ]; then
            echo "Error: Failed to generate access token"
            exit 1
          fi

          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_OUTPUT
       # env:
        #  USERNAME: ${{ secrets.USERNAME }}
         # PASSWORD: ${{ secrets.USER_PASSWORD }}

      - name: Display the extracted access_token
        run: echo "Access Token:""${{ steps.generate_token.outputs.ACCESS_TOKEN }}"
